-- Create new infinitespa_dealer_submissions table with all required fields
CREATE TABLE IF NOT EXISTS public.infinitespa_dealer_submissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Added" timestamp with time zone NOT NULL DEFAULT now(),
  "Form Type" text NOT NULL,
  "Name" text NOT NULL,
  "Email" text NOT NULL,
  "Phone" text NULL,
  "Location" text NULL,
  "Additional info" text NULL,
  CONSTRAINT infinitespa_dealer_submissions_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create index on Form Type for filtering
CREATE INDEX IF NOT EXISTS idx_infinitespa_dealer_submissions_form_type 
ON public.infinitespa_dealer_submissions("Form Type");

-- Create index on Email for searching
CREATE INDEX IF NOT EXISTS idx_infinitespa_dealer_submissions_email 
ON public.infinitespa_dealer_submissions("Email");

-- Create index on Added for sorting
CREATE INDEX IF NOT EXISTS idx_infinitespa_dealer_submissions_added 
ON public.infinitespa_dealer_submissions("Added" DESC);

-- Enable Row Level Security (RLS) if needed
ALTER TABLE public.infinitespa_dealer_submissions ENABLE ROW LEVEL SECURITY;

-- Allow public inserts (for form submissions)
CREATE POLICY "Allow public inserts on infinitespa_dealer_submissions" 
ON public.infinitespa_dealer_submissions 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- Allow authenticated users to read (for admin panel)
CREATE POLICY "Allow authenticated reads on infinitespa_dealer_submissions" 
ON public.infinitespa_dealer_submissions 
FOR SELECT 
TO authenticated 
USING (true);
